geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    #path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('description/<int:pk>', mainapp.description, name='description')
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
import random
from .models import ProductCategory, Product
from basketapp.models import Basket


def main(request, pk=None):
    hot_products = Product.objects.filter(is_hot=True).first()
    content = {'title': "Itnterior", 'hot_products': hot_products}
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    print(pk)

    title = 'продукты'
    links_menu = ProductCategory.objects.all()

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('category')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('category')

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products,
        }

        return render(request, 'mainapp/products.html', content)

    same_products = Product.objects.all()

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products
    }

    return render(request, 'mainapp/products.html', content)


def contact(request):
    products = Product.objects.all()[:6]
    content = {'title': "Contact", 'products': products}
    return render(request, 'mainapp/contact.html', content)

def description(request, pk):
    content = {
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),

    }

    return render(request, 'mainapp/description.html', content)




def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]

    return same_products

geekshop/templates/mainapp/includes/footer.html
<div class="footer">
            <div class="content">
                <img src="/static/img/footer/1.png" class="t1">
                <img src="/static/img/footer/2.png" class="t2">
                <img src="/static/img/footer/Let%E9%B3%A0Stay%20in%20Touch!.png" class="t3">
                <img src="/static/img/footer/links.png" class="t4">
                <input type="text" class="inputbox" placeholder="your email address">
                <a href="#"> <img src="/static/img/footer/but.png" class="but"></a>
                <div class="t5">&copy; COPYRYGHT - INTERIOR {% now 'Y' %}. ALL RIGHTS RESERVED</div>
                <img src="/static/img/footer/social-links.png" class="links">
                <img src="/static/img/footer/Terms%20&%20Conditions%20%20_%20%20Privacy%20policy%20&%20Cookies.png" class="t6">
            </div>
        </div>

geekshop/templates/mainapp/includes/inc_categories_menu.html
<ul class="menu_2">
  <li>
    <a href="{% url 'mainapp:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                active
              {% endif %}">
      все
    </a>
  </li>
  {% for link in links_menu %}
    <li>
      <a href="{% url 'mainapp:category' link.pk %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
        {{ link.name }}
      </a>
    </li>
  {% endfor %}
</ul>

geekshop/templates/mainapp/includes/menu.html
  <ul class="menu">
                <li><a href="{% url 'main' %}">HOME</a></li>
                <li><a href="{% url 'mainapp:index' %}">PRODUCTS</a></li>
                <li><a href="#">HISTORY</a></li>
                <li><a href="#">SHOWROOM</a></li>
                <li><a href="{% url 'contact' %}">CONTACT</a></li>
                {% if user.is_authenticated %}
<li>
    <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}
    </a>
</li>
{% endif %}
<li>
    {% if user.is_authenticated %}
      <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
      <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}
</li>
      <li>
        <a href="{% url 'basket:view' %}" class="basket">
         <img class="basket" src="/static/img/basket.png" alt="">
</a>

      </li>


</ul>

geekshop/templates/mainapp/includes/trends.html
<ul>
    {% for product in products %}
        <li><img src="/media/{{ product.image }}"><br><a href="{% url 'mainapp:description' product.pk %}" class="bt1"><p>Купить</p></a></li>
    {% endfor %}
</ul>